// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerceStarterCode.Data;

namespace eCommerceStarterCode.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211110211616_Update User")]
    partial class UpdateUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "4cf6c760-bb03-4348-805a-6ffaac32d697",
                            ConcurrencyStamp = "de99bf74-5886-4c67-ab79-274f5a70cd4a",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3455f8aa-d4b3-4935-9766-73afd019fe7f",
                            ConcurrencyStamp = "4ce831dc-6d68-4e1b-aaa4-0eea411e3ea3",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.BMP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BUN")
                        .HasColumnType("float");

                    b.Property<double>("Bicarbonate")
                        .HasColumnType("float");

                    b.Property<double>("Calcium")
                        .HasColumnType("float");

                    b.Property<double>("Chloride")
                        .HasColumnType("float");

                    b.Property<double>("Creatinine")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Glucose")
                        .HasColumnType("float");

                    b.Property<double>("Potassium")
                        .HasColumnType("float");

                    b.Property<double>("Sodium")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BMPs");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.BMPList", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BMPId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BMPId");

                    b.HasIndex("BMPId");

                    b.ToTable("BMPLists");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.CBC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Bas")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Eos")
                        .HasColumnType("float");

                    b.Property<double>("Hb")
                        .HasColumnType("float");

                    b.Property<double>("Hct")
                        .HasColumnType("float");

                    b.Property<double>("Lym")
                        .HasColumnType("float");

                    b.Property<double>("MCH")
                        .HasColumnType("float");

                    b.Property<double>("MCHC")
                        .HasColumnType("float");

                    b.Property<double>("MCV")
                        .HasColumnType("float");

                    b.Property<double>("Mon")
                        .HasColumnType("float");

                    b.Property<double>("Neu")
                        .HasColumnType("float");

                    b.Property<double>("Plt")
                        .HasColumnType("float");

                    b.Property<double>("RDW")
                        .HasColumnType("float");

                    b.Property<double>("Rbc")
                        .HasColumnType("float");

                    b.Property<double>("WBC")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CBCs");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.CBCList", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CBCId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CBCId");

                    b.HasIndex("CBCId");

                    b.ToTable("CBCLists");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionExtended")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A blood level that is below normal in potassium, an important body chemical.",
                            DescriptionExtended = "If you have hypokalemia, that means you have low levels of potassium in your blood. Potassium is a mineral your body needs to work normally. It helps muscles to move, cells to get the nutrients they need, and nerves to send their signals. It’s especially important for cells in your heart. It also helps keep your blood pressure from getting too high.",
                            Image = "https://canadianinsulin.com/wp-content/uploads/2021/05/Hypokalemia-Low-Potassium-Signs-Symptoms-Causes-and-Treatment.png",
                            Name = "Hypokalemia"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Occurs when the concentration of sodium (electrolyte) in your blood is abnormally low.",
                            DescriptionExtended = "Hyponatremia occurs when the concentration of sodium in your blood is abnormally low. Sodium is an electrolyte, and it helps regulate the amount of water that's in and around your cells.",
                            Image = "https://sarcoidosisnews.com/wp-content/uploads/2016/10/shutterstock_366005219.jpg",
                            Name = "Hyponatremia"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chronic health condition that affects how your body converts consumables into energy.",
                            DescriptionExtended = "Diabetes is a chronic (long-lasting) health condition that affects how your body turns food into energy. Most of the food you eat is broken down into sugar(also called glucose) and released into your bloodstream.When your blood sugar goes up, it signals your pancreas to release insulin.Insulin acts like a key to let the blood sugar into your body’s cells for use as energy. If you have diabetes, your body either doesn’t make enough insulin or can’t use the insulin it makes as well as it should.When there isn’t enough insulin or cells stop responding to insulin, too much blood sugar stays in your bloodstream.",
                            Image = "https://solutionpharmacy.in/wp-content/uploads/2021/05/Diabetes-mellitus-1024x670.jpg",
                            Name = "Diabetes Mellitus"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Glomerulonephritis is a group of diseases that injure the part of the kidney that filters blood (called glomeruli).",
                            DescriptionExtended = "Glomerulonephritis is a group of diseases that injure the part of the kidney that filters blood (called glomeruli). Other terms you may hear used are nephritis and nephrotic syndrome. When the kidney is injured, it cannot get rid of wastes and extra fluid in the body. If the illness continues, the kidneys may stop working completely, resulting in kidney failure.",
                            Image = "https://www.mayoclinic.org/-/media/kcms/gbs/patient-consumer/images/2013/11/15/17/35/ds00280_-ds00360_-ds00503_-ds00682_-ds00856_-ds01047_im00767_r7_kidneysectionthu_2_jpg.jpg",
                            Name = "Glomerulonephritis"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Alkalosis occurs when your body has too many bases.",
                            DescriptionExtended = "Alkalosis occurs when your body has too many bases. It can occur due to decreased blood levels of carbon dioxide, which is an acid. It can also occur due to increased blood levels of bicarbonate, which is a base. This condition has a variety of origins such as metabolic and respiratory",
                            Image = "https://pharmacygyan.com/wp-content/uploads/2020/03/20200301_094733.jpg",
                            Name = "Alkalosis"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Disease state caused by bacteria-propagated pathogenicity",
                            DescriptionExtended = "Bacteria are living things that have only one cell. Under a microscope, they look like balls, rods, or spirals. They are so small that a line of 1,000 could fit across a pencil eraser. Most types of don't make you sick. Many types are helpful. Some of them help to digest food, destroy disease-causing cells, and give the body needed vitamins. Bacteria are also used in making healthy foods like yogurt and cheese. But infectious bacteria can make you ill.They reproduce quickly in your body.Many give off chemicals called toxins, which can damage tissue and make you sick.Examples of bacteria that cause infections include Streptococcus, Staphylococcus, and E.coli.",
                            Image = "https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/video/incremental_bacterial_and_viral_infections_video/650x350_incremental_bacterial_and_viral_infections_video.jpg",
                            Name = "Bacterial Infection"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Mononucleosis (mono) is a contagious infection caused by a herpes virus called Epstein-Barr.",
                            DescriptionExtended = "Mononucleosis is an illness that commonly affects teenagers and young adults, but can affect children as well. Viruses, most commonly Epstein-Barr Virus (EBV), and certain infections cause the illness. Mono is sometimes called “the kissing disease” because it spreads easily through bodily fluids like saliva.",
                            Image = "https://www.microscopyu.com/assets/gallery-images/pathology_mononucleosis40x02.jpg",
                            Name = "Mononucleosis"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Anemia is a condition in which you lack enough healthy red blood cells to carry adequate oxygen to your body's tissues.",
                            DescriptionExtended = "Anemia is a condition in which you lack enough healthy red blood cells to carry adequate oxygen to your body's tissues. Having anemia, also referred to as low hemoglobin, can make you feel tired and weak. There are many forms of anemia, each with its own cause.Anemia can be temporary or long term and can range from mild to severe.In most cases, anemia has more than one cause.",
                            Image = "https://images.emedicinehealth.com/images/article/main_image/anemia-1.jpg",
                            Name = "Anemia"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Immune thrombocytopenia (ITP) is a disorder that can lead to easy or excessive bruising and bleeding.",
                            DescriptionExtended = "Immune thrombocytopenia (ITP) is a disorder that can lead to easy or excessive bruising and bleeding. The bleeding results from unusually low levels of platelets — the cells that help blood clot. Formerly known as idiopathic thrombocytopenic purpura,ITP can cause purple bruises, as well as tiny reddish - purple dots that look like a rash.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8yaSvH3nV1h9Z7r6ViZrw3RB84iO-t_vCDA&usqp=CAU",
                            Name = "Immune Thrombocytopenia"
                        });
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.ConditionList", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ConditionId");

                    b.HasIndex("ConditionId");

                    b.ToTable("ConditionLists");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("eCommerceStarterCode.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("eCommerceStarterCode.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerceStarterCode.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("eCommerceStarterCode.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.BMPList", b =>
                {
                    b.HasOne("eCommerceStarterCode.Models.BMP", "BMP")
                        .WithMany()
                        .HasForeignKey("BMPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerceStarterCode.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BMP");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.CBCList", b =>
                {
                    b.HasOne("eCommerceStarterCode.Models.CBC", "CBC")
                        .WithMany()
                        .HasForeignKey("CBCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerceStarterCode.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CBC");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.ConditionList", b =>
                {
                    b.HasOne("eCommerceStarterCode.Models.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerceStarterCode.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerceStarterCode.Models.Profile", b =>
                {
                    b.HasOne("eCommerceStarterCode.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
